# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Data = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Data.setGeometry(QtCore.QRect(180, 180, 230, 51))
        self.Data.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Data.setObjectName("Data")
        self.Analytics = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Analytics.setGeometry(QtCore.QRect(180, 240, 230, 51))
        self.Analytics.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Analytics.setObjectName("Analytics")
        self.Financ = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Financ.setGeometry(QtCore.QRect(180, 300, 230, 51))
        self.Financ.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Financ.setObjectName("Financ")
        self.Help = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Help.setGeometry(QtCore.QRect(180, 490, 230, 51))
        self.Help.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Help.setObjectName("Help")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Data.setText(_translate("MainWindow", "Данные"))
        self.Analytics.setText(_translate("MainWindow", "Аналитика"))
        self.Financ.setText(_translate("MainWindow", "Финансирование"))
        self.Help.setText(_translate("MainWindow", "Помощь"))
        self.label.setText(_translate("MainWindow", "Главное меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
